
package org.soa.ws.tp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceCRUDImplService", targetNamespace = "http://tp.ws.soa.org/", wsdlLocation = "http://localhost:1234/crud?wsdl")
public class WebServiceCRUDImplService
    extends Service
{

    private final static URL WEBSERVICECRUDIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECRUDIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICECRUDIMPLSERVICE_QNAME = new QName("http://tp.ws.soa.org/", "WebServiceCRUDImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/crud?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECRUDIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICECRUDIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceCRUDImplService() {
        super(__getWsdlLocation(), WEBSERVICECRUDIMPLSERVICE_QNAME);
    }

    public WebServiceCRUDImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECRUDIMPLSERVICE_QNAME, features);
    }

    public WebServiceCRUDImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECRUDIMPLSERVICE_QNAME);
    }

    public WebServiceCRUDImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECRUDIMPLSERVICE_QNAME, features);
    }

    public WebServiceCRUDImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCRUDImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceCRUD
     */
    @WebEndpoint(name = "WebServiceCRUDImplPort")
    public WebServiceCRUD getWebServiceCRUDImplPort() {
        return super.getPort(new QName("http://tp.ws.soa.org/", "WebServiceCRUDImplPort"), WebServiceCRUD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCRUD
     */
    @WebEndpoint(name = "WebServiceCRUDImplPort")
    public WebServiceCRUD getWebServiceCRUDImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tp.ws.soa.org/", "WebServiceCRUDImplPort"), WebServiceCRUD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECRUDIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICECRUDIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICECRUDIMPLSERVICE_WSDL_LOCATION;
    }

}
