
package org.soa.ws.tp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceCRUD", targetNamespace = "http://tp.ws.soa.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceCRUD {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readCategProduct", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.ReadCategProduct")
    @ResponseWrapper(localName = "readCategProductResponse", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.ReadCategProductResponse")
    @Action(input = "http://tp.ws.soa.org/WebServiceCRUD/readCategProductRequest", output = "http://tp.ws.soa.org/WebServiceCRUD/readCategProductResponse")
    public String readCategProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
